services:
  file-storage-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: file-storage-api-student1

    ports:
      - "9001:9001"

    env_file:
      - .env

    restart: always

    networks:
      - be_classroom_net

networks:
  be_classroom_net:
    external: true