services:
  file-storage-api:
    image: ${DOCKERHUB_USERNAME}/file-storage-api-student1:latest

    container_name: file-storage-api-student1

    ports:
      - "${APP_PORT:-9001}:${APP_PORT:-9001}"

    env_file:
      - .env

    restart: always

    networks:
      - be_classroom_net

networks:
  be_classroom_net:
    external: true